services:
  - type: web
    name: ESPN_CLONE
    env: static
    buildCommand: npm run build
    startCommand: npx serve -s dist
    publishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18
