services:
  - type: web
    name: nfl-feed
    runtime: static
    staticPublishPath: dist
    buildCommand: npm run build
    envVars:
      - key: NODE_VERSION
        value: 18
    redirects:
      - source: '/*'
        destination: '/index.html'
        statusCode: 200
