services:
  - type: web
    name: your-service-name
    env: node
    buildCommand: npm run build
    startCommand: npx serve -s dist
    publishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18
